### ISSUE TITLE
vcf coordinate liftover

### ISSUE THREAD

**Issue by dongyiyi** [enormandeau/snplift#7]
Hi Eric,

Thank you for developing this pipeline!

I had a reference genome A with large chromosomes, so I had to shorten the chromosomes (less than 512 MB), and then I got a "new reference genome B.". I got my final vcf.gz file after running the SNP calling and filtering with gatk. Now, I try to convert my vcf coordinates from genome B to genome A. For my understanding, the BAM index format seems to not fit the reference sequence above 512 MB, which means this pipeline also only handles the small chromosome length. Am I right? I guess this pipeline will not work for my case, but I have not tested it yet.

Thanks!

**Comment by enormandeau** [comment]
Hi,

If I understand properly, reference B is identical to A except that the scaffolds have been split and renamed. In this case,it would be best for you to correct the positions given the exact information of how your scaffolds were split and renamed rather than use SNPLift. This would ensure you get the proper positions for all the SNPs, something SNPLift cannot guaranty.

Take care.
